module.exports = {
	"rotisserie chicken": "rotisserie_chicken", 
	"milk bars": "milkbars", 
	"tapas": "tapasmallplates",
	"small plates": "tapasmallplates", 
	"fondue": "fondue", 
	"buffets": "buffets", 
	"gluten-free": "gluten_free", 
	"arabian": "arabian", 
	"oriental": "oriental", 
	"curry sausage": "currysausage", 
	"creperies": "creperies", 
	"poutineries": "poutineries", 
	"argentine": "argentine", 
	"belgian": "belgian", 
	"baguettes": "baguettes", 
	"bulgarian": "bulgarian", 
	"modern australian": "modern_australian", 
	"polish": "polish", 
	"freiduria": "freiduria", 
	"french": "french", 
	"armenian": "armenian", 
	"thai": "thai", 
	"lyonnais": "lyonnais", 
	"night food": "nightfood", 
	"bistros": "bistros", 
	"filipino": "filipino", 
	"swiss food": "swissfood", 
	"new zealand": "newzealand", 
	"traditional swedish": "traditional_swedish", 
	"persian": "persian",
	"iranian": "persian", 
	"italian": "italian", 
	"steakhouses": "steak", 
	"fischbroetchen": "fischbroetchen", 
	"american traditional": "tradamerican", 
	"traditional american": "tradamerican", 
	"pf": "pfcomercial",
	"comercial": "pfcomercial", 
	"mediterranean": "mediterranean", 
	"moroccan": "moroccan", 
	"galician": "galician", 
	"dumplings": "dumplings",
	"delis": "delis", 
	"halal": "halal", 
	"scottish": "scottish", 
	"austrian": "austrian", 
	"noodles": "noodles", 
	"tex-mex": "tex-mex", 
	"sandwiches": "sandwiches", 
	"swedish": "swedish", 
	"signature cuisine": "signature_cuisine",
	"parent cafes": "eltern_cafes", 
	"caribbean": "caribbean", 
	"american new": "newamerican", 
	"new american": "newamerican", 
	"american": "newamerican",
	"meatballs": "meatballs", 
	"french southwest": "sud_ouest", 
	"pan asian": "panasian", 
	"breakfast and brunch": "breakfast_brunch", 
	"breakfast": "breakfast_brunch", 
	"brunch": "breakfast_brunch", 
	"venison": "venison", 
	"food stands": "foodstands", 
	"wok": "wok", 
	"laos": "laos", 
	"international": "international", 
	"rice": "riceshop", 
	"pop-up restaurants": "popuprestaurants", 
	"danish": "danish", 
	"beer hall": "beerhall", 
	"hawaiian": "hawaiian", 
	"cheesesteaks": "cheesesteaks", 
	"supper clubs": "supperclubs", 
	"iberian": "iberian", 
	"tapas bars": "tapas", 
	"slovakian": "slovakian", 
	"canadian new": "newcanadian", 
	"canadian": "newcanadian",
	"potatoes": "potatoes", 
	"open sandwiches": "opensandwiches", 
	"black sea": "blacksea", 
	"game meat": "gamemeat", 
	"yugoslav": "yugoslav", 
	"fish and chips": "fishnchips", 
	"chilean": "chilean", 
	"cuban": "cuban", 
	"cajun": "cajun",
	"creole": "cajun", 
	"eastern european": "eastern_european", 
	"uzbek": "uzbek", 
	"cafes": "cafes", 
	"scandinavian": "scandinavian", 
	"burgers": "burgers", 
	"burmese": "burmese", 
	"african": "african", 
	"island pub": "island_pub", 
	"heuriger": "heuriger", 
	"flatbread": "flatbread", 
	"singaporean": "singaporean", 
	"chinese": "chinese", 
	"greek": "greek", 
	"asian fusion": "asianfusion", 
	"nikkei": "nikkei", 
	"bavarian": "bavarian", 
	"ethiopian": "ethiopian", 
 	"syrian": "syrian", 
 	"wraps": "wraps", 
 	"turkish": "turkish", 
 	"middle eastern": "mideastern", 
	"live food": "raw_food", 
	"raw food": "raw_food", 
	"bangladeshi": "bangladeshi", 
	"schnitzel": "schnitzel", 
	"indian": "indpak", 
	"latin american": "latin", 
	"brazilian": "brazilian", 
	"chicken wings": "chicken_wings", 
	"korean": "korean", 
	"pakistani": "pakistani", 
	"barbeque": "bbq", 
	"hungarian": "hungarian", 
	"brasseries": "brasseries", 
	"swabian": "swabian", 
	"southern": "southern", 
	"vegan": "vegan", 
	"catalan": "catalan", 
	"diners": "diners", 
	"new mexican cuisine": "newmexican", 
	"gastropubs": "gastropubs", 
	"afghan": "afghani", 
	"kebab": "kebab", 
	"serbo croatian": "serbocroatian", 
	"vegetarian": "vegetarian", 
	"malaysian": "malaysian", 
	"chicken shop": "chickenshop", 
	"kosher": "kosher", 
	"russian": "russian", 
	"modern european": "modern_european", 
	"pita": "pita", 
	"hong kong style cafe": "hkcafe", 
	"traditional norwegian": "norwegian", 
	"giblets": "giblets", 
	"irish": "irish", 
	"cypriot": "cypriot", 
	"german": "german", 
	"taiwanese": "taiwanese", 
	"czech": "czech", 
	"andalusian": "andalusian", 
	"laotian": "laotian", 
	"mongolian": "mongolian", 
	"basque": "basque", 
	"canteen": "canteen", 
	"guamanian": "guamanian", 
	"israeli": "israeli", 
	"norcinerie": "norcinerie", 
	"vietnamese": "vietnamese",
	"romanian": "romanian", 
	"corsican": "corsican", 
	"waffles": "waffles", 
	"fast food": "hotdogs", 
	"australian": "australian", 
	"food court": "food_court", 
	"salad": "salad", 
	"ukrainian": "ukrainian", 
	"jewish": "jewish", 
	"sushi bars": "sushi", 
	"sushi": "sushi",
	"himalayan": "himalayan", 
	"nepalese": "himalayan", 
	"beisl": "beisl", 
	"kopitiam": "kopitiam", 
	"pizza": "pizza", 
	"tavola calda": "tavolacalda", 
	"kurdish": "kurdish", 
	"beer garden": "beergarden", 
	"dinner theater": "dinnertheater", 
	"seafood": "seafood", 
	"pub food": "pubfood", 
	"indonesian": "indonesian", 
	"british": "british", 
	"trattorie": "trattorie", 
	"soup": "soup", 
	"asturian": "asturian", 
	"tabernas": "tabernas", 
	"hot pot": "hotpot", 
	"comfort food": "comfortfood", 
	"portuguese": "portuguese", 
	"nicaraguan": "nicaraguan", 
	"mexican": "mexican", 
	"peruvian": "peruvian", 
	"sri lankan": "srilankan", 
	"japanese": "japanese", 
	"parma": "parma", 
	"cambodian": "cambodian", 
	"hot dogs": "hotdog", 
	"spanish": "spanish", 
	"honduran": "honduran", 
	"cafeteria": "cafeteria", 
	"georgian": "georgian", 
	"soul food": "soulfood"
};