module.exports = {
	"Rotisserie Chicken": "rotisserie_chicken", 
	"Milk Bars": "milkbars", 
	"Tapas/Small Plates": "tapasmallplates", 
	"Fondue": "fondue", 
	"Buffets": "buffets", 
	"Gluten-Free": "gluten_free", 
	"Arabian": "arabian", 
	"Oriental": "oriental", 
	"Curry Sausage": "currysausage", 
	"Creperies": "creperies", 
	"Poutineries": "poutineries", 
	"Argentine": "argentine", 
	"Belgian": "belgian", 
	"Baguettes": "baguettes", 
	"Bulgarian": "bulgarian", 
	"Modern Australian": "modern_australian", 
	"Polish": "polish", 
	"Freiduria": "freiduria", 
	"French": "french", 
	"Armenian": "armenian", 
	"Thai": "thai", 
	"Lyonnais": "lyonnais", 
	"Night Food": "nightfood", 
	"Bistros": "bistros", 
	"Filipino": "filipino", 
	"Swiss Food": "swissfood", 
	"New Zealand": "newzealand", 
	"Traditional Swedish": "traditional_swedish", 
	"Persian/Iranian": "persian", 
	"Italian": "italian", 
	"Steakhouses": "steak", 
	"Fischbroetchen": "fischbroetchen", 
	"American (Traditional)": "tradamerican", 
	"PF/Comercial": "pfcomercial", 
	"Mediterranean": "mediterranean", 
	"Moroccan": "moroccan", 
	"Galician": "galician", 
	"Dumplings": "dumplings",
	"Delis": "delis", 
	"Halal": "halal", 
	"Scottish": "scottish", 
	"Austrian": "austrian", 
	"Noodles": "noodles", 
	"Tex-Mex": "tex-mex", 
	"Sandwiches": "sandwiches", 
	"Swedish": "swedish", 
	"Signature Cuisine": "signature_cuisine",
	"Parent Cafes": "eltern_cafes", 
	"Caribbean": "caribbean", 
	"American (New)": "newamerican", 
	"Meatballs": "meatballs", 
	"French Southwest": "sud_ouest", 
	"Pan Asian": "panasian", 
	"Breakfast & Brunch": "breakfast_brunch", 
	"Venison": "venison", 
	"Food Stands": "foodstands", 
	"Wok": "wok", 
	"Laos": "laos", 
	"International": "international", 
	"Rice": "riceshop", 
	"Pop-Up Restaurants": "popuprestaurants", 
	"Danish": "danish", 
	"Beer Hall": "beerhall", 
	"Hawaiian": "hawaiian", 
	"Cheesesteaks": "cheesesteaks", 
	"Supper Clubs": "supperclubs", 
	"Iberian": "iberian", 
	"Tapas Bars": "tapas", 
	"Slovakian": "slovakian", 
	"Canadian (New)": "newcanadian", 
	"Potatoes": "potatoes", 
	"Open Sandwiches": "opensandwiches", 
	"Black Sea": "blacksea", 
	"Game Meat": "gamemeat", 
	"Yugoslav": "yugoslav", 
	"Fish & Chips": "fishnchips", 
	"Chilean": "chilean", 
	"Cuban": "cuban", 
	"Cajun/Creole": "cajun", 
	"Eastern European": "eastern_european", 
	"Uzbek": "uzbek", 
	"Cafes": "cafes", 
	"Scandinavian": "scandinavian", 
	"Burgers": "burgers", 
	"Burmese": "burmese", 
	"African": "african", 
	"Island Pub": "island_pub", 
	"Heuriger": "heuriger", 
	"Flatbread": "flatbread", 
	"Singaporean": "singaporean", 
	"Chinese": "chinese", 
	"Greek": "greek", 
	"Asian Fusion": "asianfusion", 
	"Nikkei": "nikkei", 
	"Bavarian": "bavarian", 
	"Ethiopian": "ethiopian", 
 	"Syrian": "syrian", 
 	"Wraps": "wraps", 
 	"Turkish": "turkish", 
 	"Middle Eastern": "mideastern", 
	"Live/Raw Food": "raw_food", 
	"Bangladeshi": "bangladeshi", 
	"Schnitzel": "schnitzel", 
	"Indian": "indpak", 
	"Latin American": "latin", 
	"Brazilian": "brazilian", 
	"Chicken Wings": "chicken_wings", 
	"Korean": "korean", 
	"Pakistani": "pakistani", 
	"Barbeque": "bbq", 
	"Hungarian": "hungarian", 
	"Brasseries": "brasseries", 
	"Swabian": "swabian", 
	"Southern": "southern", 
	"Vegan": "vegan", 
	"Catalan": "catalan", 
	"Diners": "diners", 
	"New Mexican Cuisine": "newmexican", 
	"Gastropubs": "gastropubs", 
	"Afghan": "afghani", 
	"Kebab": "kebab", 
	"Serbo Croatian": "serbocroatian", 
	"Vegetarian": "vegetarian", 
	"Malaysian": "malaysian", 
	"Chicken Shop": "chickenshop", 
	"Kosher": "kosher", 
	"Russian": "russian", 
	"Modern European": "modern_european", 
	"Pita": "pita", 
	"Hong Kong Style Cafe": "hkcafe", 
	"Traditional Norwegian": "norwegian", 
	"Giblets": "giblets", 
	"Irish": "irish", 
	"Cypriot": "cypriot", 
	"German": "german", 
	"Taiwanese": "taiwanese", 
	"Czech/Slovakian": "czechslovakian", 
	"Czech": "czech", 
	"Andalusian": "andalusian", 
	"Laotian": "laotian", 
	"Mongolian": "mongolian", 
	"Basque": "basque", 
	"Canteen": "canteen", 
	"Guamanian": "guamanian", 
	"Israeli": "israeli", 
	"Norcinerie": "norcinerie", 
	"Vietnamese": "vietnamese", 
	"Romanian": "romanian", 
	"Corsican": "corsican", 
	"Waffles": "waffles", 
	"Fast Food": "hotdogs", 
	"Australian": "australian", 
	"Food Court": "food_court", 
	"Salad": "salad", 
	"Ukrainian": "ukrainian", 
	"Jewish": "jewish", 
	"Sushi Bars": "sushi", 
	"Himalayan/Nepalese": "himalayan", 
	"Beisl": "beisl", 
	"Kopitiam": "kopitiam", 
	"Pizza": "pizza", 
	"Tavola Calda": "tavolacalda", 
	"Kurdish": "kurdish", 
	"Beer Garden": "beergarden", 
	"Dinner Theater": "dinnertheater", 
	"Seafood": "seafood", 
	"Pub Food": "pubfood", 
	"Indonesian": "indonesian", 
	"British": "british", 
	"Trattorie": "trattorie", 
	"Soup": "soup", 
	"Asturian": "asturian", 
	"Tabernas": "tabernas", 
	"Hot Pot": "hotpot", 
	"Comfort Food": "comfortfood", 
	"Portuguese": "portuguese", 
	"Nicaraguan": "nicaraguan", 
	"Mexican": "mexican", 
	"Peruvian": "peruvian", 
	"Sri Lankan": "srilankan", 
	"Japanese": "japanese", 
	"Parma": "parma", 
	"Cambodian": "cambodian", 
	"Hot Dogs": "hotdog", 
	"Spanish": "spanish", 
	"Honduran": "honduran", 
	"Cafeteria": "cafeteria", 
	"Georgian": "georgian", 
	"Soul Food": "soulfood"
};